//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookExchangerWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookExchangerDBEntities : DbContext
    {
        public BookExchangerDBEntities()
            : base("name=BookExchangerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<DeleveryDetail> DeleveryDetails { get; set; }
        public virtual DbSet<DeleveryMan> DeleveryMen { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<RequestedBook> RequestedBooks { get; set; }
        public virtual DbSet<SellPosting> SellPostings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
