//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookExchangerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleveryDetail
    {
        public int DeleveryId { get; set; }
        public int SellId { get; set; }
        public int DeleveryManId { get; set; }
        public System.DateTime BookReceivedDate { get; set; }
        public Nullable<System.DateTime> BookDeleverdDate { get; set; }
    }
}
