//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookExchangerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellPosting
    {
        public int SellId { get; set; }
        public int BuyerId { get; set; }
        public int SellerId { get; set; }
        public int BookId { get; set; }
        public int Status { get; set; }
    }
}
